#定义一个变量
#使用缩进表示层级关系
USER:
  NAME2: zhangsan #数值前一定要有一个空格

#键值对
#person:
#  name: 张三
#  age:我门来使用动态代理实现代理我们后面写的UserService 18
#单行配置
person: {name: 张三,age: 19}

#数组
address:
  - 北京
  - 上海
  - 广东
#单行配置
#address2 : [北京,上海,广东]

#纯量(常量值)
msg1: 'Hello \n world' #单引号忽略转义字符
msg2: "Hello \n world" #双引识别转义字符

#参数引用
name: ${USER.NAME2}

#init 在pojo.Man 添加@ConfigurationProperties(prefix = "init.man")
init:
  man:
    username: 路飞
    boss: true
    birth: 1999/03/09 10:00:00
    age: 22
    address: [广东,上海,北京]
    addressList: [佛山,深圳,广州]
    hobbies:
      sports: [basketball,football]
      play: [dnf,cf,qqspeed]
    woman:
      username: 娜美
      age: 22
      address: [swing,sex]