server:
  port: 8080

spring:
  application:
    name: user-consumer

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}

logging:
  level:
    com.happy233: debug

# 局部配置,配置负载均衡策略 IRule接口的实现类的全限定名
#user-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
# 全局配置,配置负载均衡策略
#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
