#激活环境 dev 填写配置文件名-后面的内容即可
#环境切换方式1.
spring:
  profiles:
    active: test
#环境切换方式2. 在启动配置中配置VM options: -Dspring。profiles.active=xxx

#环境切换方式3. 以jar包方式启动 package后会在target目录生成jar包 使用命令行(本地或idea自带命令行) java- [jar包名称] --spring.profiles.active=xxx

#项目内部的配置文件加载顺序
#resource/config 中的 applicatiom.yml比类路径下的优先级更高
#项目路径比工程(模块)路径config更高
#项目路径/config比项目路径的更高

#项目外部的配置文件加载顺序
#命令行方式 打成jar包后 java [jar包名称] 优先级顺序 jar同级目录/config下>jar包同级目录下>jar包中的config下>jar包resource下(类路径下)