server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka #注册中心地址 集群使用,分割
  instance:
    ip-address: 127.0.0.1 #ip地址
    prefer-ip-address: true #更倾向于ip 而不是host名
    instance-id: ${eureka.instance.ip-address}:${server.port} #自定义实例id

#配置数据源
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eslearn
    username: root
    password: 1234

mybatis:
  type-aliases-package: com.happy233.pojo
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射

#日志等级
logging:
  level:
    com.happy233: debug